#!/usr/bin/bash
error(){
    echo "install error:" "$@" >&2
    exit 1
}

run(){
    echo "install:" "$@"
    "$@"
}

for program in python pipx poetry; do
    if ! command -v "$program" >/dev/null 2>&1; then
        echo "required: $program" >&2
        missing=1
    fi
done
[[ -n "$missing" ]] && exit 1

ROOT_DIR=$(dirname "$(dirname "$(realpath "$0")")")
cd "$ROOT_DIR" || error "couldn't find project root"
[[ -d ./dist ]] && run rm -rf ./dist
run poetry install --only main
run poetry build --format wheel -o ./dist
run pipx install ./dist/*

echo "install: Installation complete!"
