# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: ROT13 documentation
theme:
  name: material
nav:
  - Getting started: index.md
  - License: ../../LICENSE
